#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'weari/thrift/weari_types'

        module Weari
          module Thrift
            module Server
              class Client
                include ::Thrift::Client

                def ping()
                  send_ping()
                  recv_ping()
                end

                def send_ping()
                  send_message('ping', Ping_args)
                end

                def recv_ping()
                  result = receive_message(Ping_result)
                  return
                end

                def index(solr, filter, arcs, extraId, extraFields)
                  send_index(solr, filter, arcs, extraId, extraFields)
                  recv_index()
                end

                def send_index(solr, filter, arcs, extraId, extraFields)
                  send_message('index', Index_args, :solr => solr, :filter => filter, :arcs => arcs, :extraId => extraId, :extraFields => extraFields)
                end

                def recv_index()
                  result = receive_message(Index_result)
                  raise result.ex1 unless result.ex1.nil?
                  raise result.ex2 unless result.ex2.nil?
                  return
                end

                def parseArcs(arcs)
                  send_parseArcs(arcs)
                  recv_parseArcs()
                end

                def send_parseArcs(arcs)
                  send_message('parseArcs', ParseArcs_args, :arcs => arcs)
                end

                def recv_parseArcs()
                  result = receive_message(ParseArcs_result)
                  return
                end

                def isArcParsed(arc)
                  send_isArcParsed(arc)
                  return recv_isArcParsed()
                end

                def send_isArcParsed(arc)
                  send_message('isArcParsed', IsArcParsed_args, :arc => arc)
                end

                def recv_isArcParsed()
                  result = receive_message(IsArcParsed_result)
                  return result.success unless result.success.nil?
                  raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'isArcParsed failed: unknown result')
                end

              end

              class Processor
                include ::Thrift::Processor

                def process_ping(seqid, iprot, oprot)
                  args = read_args(iprot, Ping_args)
                  result = Ping_result.new()
                  @handler.ping()
                  write_result(result, oprot, 'ping', seqid)
                end

                def process_index(seqid, iprot, oprot)
                  args = read_args(iprot, Index_args)
                  result = Index_result.new()
                  begin
                    @handler.index(args.solr, args.filter, args.arcs, args.extraId, args.extraFields)
                  rescue Weari::Thrift::IndexException => ex1
                    result.ex1 = ex1
                  rescue Weari::Thrift::UnparsedException => ex2
                    result.ex2 = ex2
                  end
                  write_result(result, oprot, 'index', seqid)
                end

                def process_parseArcs(seqid, iprot, oprot)
                  args = read_args(iprot, ParseArcs_args)
                  result = ParseArcs_result.new()
                  @handler.parseArcs(args.arcs)
                  write_result(result, oprot, 'parseArcs', seqid)
                end

                def process_isArcParsed(seqid, iprot, oprot)
                  args = read_args(iprot, IsArcParsed_args)
                  result = IsArcParsed_result.new()
                  result.success = @handler.isArcParsed(args.arc)
                  write_result(result, oprot, 'isArcParsed', seqid)
                end

              end

              # HELPER FUNCTIONS AND STRUCTURES

              class Ping_args
                include ::Thrift::Struct, ::Thrift::Struct_Union

                FIELDS = {

                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

              class Ping_result
                include ::Thrift::Struct, ::Thrift::Struct_Union

                FIELDS = {

                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

              class Index_args
                include ::Thrift::Struct, ::Thrift::Struct_Union
                SOLR = 1
                FILTER = 2
                ARCS = 3
                EXTRAID = 4
                EXTRAFIELDS = 5

                FIELDS = {
                  SOLR => {:type => ::Thrift::Types::STRING, :name => 'solr'},
                  FILTER => {:type => ::Thrift::Types::STRING, :name => 'filter'},
                  ARCS => {:type => ::Thrift::Types::LIST, :name => 'arcs', :element => {:type => ::Thrift::Types::STRING}},
                  EXTRAID => {:type => ::Thrift::Types::STRING, :name => 'extraId'},
                  EXTRAFIELDS => {:type => ::Thrift::Types::MAP, :name => 'extraFields', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRING}}
                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

              class Index_result
                include ::Thrift::Struct, ::Thrift::Struct_Union
                EX1 = 1
                EX2 = 2

                FIELDS = {
                  EX1 => {:type => ::Thrift::Types::STRUCT, :name => 'ex1', :class => Weari::Thrift::IndexException},
                  EX2 => {:type => ::Thrift::Types::STRUCT, :name => 'ex2', :class => Weari::Thrift::UnparsedException}
                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

              class ParseArcs_args
                include ::Thrift::Struct, ::Thrift::Struct_Union
                ARCS = 1

                FIELDS = {
                  ARCS => {:type => ::Thrift::Types::LIST, :name => 'arcs', :element => {:type => ::Thrift::Types::STRING}}
                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

              class ParseArcs_result
                include ::Thrift::Struct, ::Thrift::Struct_Union

                FIELDS = {

                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

              class IsArcParsed_args
                include ::Thrift::Struct, ::Thrift::Struct_Union
                ARC = 1

                FIELDS = {
                  ARC => {:type => ::Thrift::Types::STRING, :name => 'arc'}
                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

              class IsArcParsed_result
                include ::Thrift::Struct, ::Thrift::Struct_Union
                SUCCESS = 0

                FIELDS = {
                  SUCCESS => {:type => ::Thrift::Types::BOOL, :name => 'success'}
                }

                def struct_fields; FIELDS; end

                def validate
                end

                ::Thrift::Struct.generate_accessors self
              end

            end

          end
        end
