#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module Weari
  module Thrift
        class IndexException < ::Thrift::Exception
          include ::Thrift::Struct, ::Thrift::Struct_Union
          def initialize(message=nil)
            super()
            self.why = message
          end

          def message; why end

          WHY = 1

          FIELDS = {
            WHY => {:type => ::Thrift::Types::STRING, :name => 'why'}
          }

          def struct_fields; FIELDS; end

          def validate
          end

          ::Thrift::Struct.generate_accessors self
        end

        class UnparsedException < ::Thrift::Exception
          include ::Thrift::Struct, ::Thrift::Struct_Union
          def initialize(message=nil)
            super()
            self.arcname = message
          end

          def message; arcname end

          ARCNAME = 1

          FIELDS = {
            ARCNAME => {:type => ::Thrift::Types::STRING, :name => 'arcname'}
          }

          def struct_fields; FIELDS; end

          def validate
          end

          ::Thrift::Struct.generate_accessors self
        end

      end
    end
